# Generated by Django 5.0 on 2026-05-23 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('ranking', models.IntegerField(default=1000, verbose_name='Ranking ELO')),
                ('registered_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['-ranking', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('white_wins', 'Las Blancas Ganan'), ('black_wins', 'Las Negras Ganan'), ('draw', 'Empate')], default='draw', max_length=20, verbose_name='Resultado')),
                ('played_at', models.DateField(verbose_name='Fecha de la Partida')),
                ('opening', models.CharField(blank=True, max_length=200, verbose_name='Apertura')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to='chess.player', verbose_name='Jugador Negras')),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to='chess.player', verbose_name='Jugador Blancas')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['-played_at'],
            },
        ),
    ]
